cybozu/eslint-config

README.md, globals/kintone.js, lib/kintone.js, presets/kintone-customize-es5-prettier.js, presets/kintone-customize-es5.js, test/fixtures/es5/ok.js, test/fixtures/es5/warning.js, test/fixtures/globals-kintone/error.js, test/fixtures/globals-kintone/ok.js, test/fixtures/kintone/error.js, test/fixtures/kintone/ok.js, test/globals-kintone-test.js, test/kintone-test.js, test/presets-test.js
This PR introduces `kintone-customize-es5`, which is for developers of kintone customize(plugins).
You can use `kintone-customize-es5` as `@cybozu/eslint-config/presets/kintone-customize-es5`.
=> feat: add kintone-customize-es5

lib/base.js, test/fixtures/base/ok.js
I've noticed that `$.Deferred()` is reported as `new-cap` violation so I want to add `capIsNewExceptions` for `$.Deferred()`
=> feat: allow $.Deferred for new-cap

lib/typescript.js, test/react-typescript-test.js, test/typescript-test.js
We've added TypeScript support as #97, which is enabled rules that is required type information so we have to add `parserOptions.project` into our `.eslintrc.js`.
But lint with the option is 5〜10x slower than without it, which is not an  acceptable regression for us so we've decided to disable all rules required type information.
=> fix(perf): typescript: disable rules required type infomation

README.md, lib/base.js, lib/react.js, package-lock.json, package.json
This is a **BREAKING CHANGE** for React users because this causes new errors for code using React Hooks.
I've also added many a11y rules as warnings, but I might disable some rules if they don't make sense.
So please file an issue if you encounter rules that you feel they don't make sense.
=> Add react-hooks and jsx-a11y

lib/react-typescript.js, test/fixtures/react-typescript/ok.tsx
When Using React and TypeScript, `propTypes` is rarely used.
I want to disable `react/prop-types`
=> feat(react-typescript): disable prop-types

package.json
BREAKING CHANGE: dropping eslint v5,eslint v6 only supporting
=> feat!: drop eslint v5

lib/typescript.js, test/fixtures/typescript/ok.ts
I know `@ts-ignore` isn't good, but sometimes we need it at refactoring legacy code and using npm packages that have wrong type definitions, and so on.
So I want to allow to use `@ts-ignore`.
=> feat(typescript): disable typescript-eslint/ban-ts-ignore

lib/base.js, package.json, test/base-test.js, test/fixtures/base/error.js
**PLEASE DO NOT SQUASH MERGE**
This PR contains some BREAKING CHANGES so I'd like to release a new version that doesn't include this.
~**Please do not merge this before publishing a new version.**~
I've released a new version already
This PR enables rules added ESLint v6.4.0 so this has the following BREAKING CHANGES
- Update your ESLint version to v6.4.0
- You might see new errors after updating `cybozu/eslint-config`
https://eslint.org/blog/2019/09/eslint-v6.4.0-released
=> Update ESLint version to v6.4.0 and enable new rules

lib/node.js, test/fixtures/node-typescript/error.ts, test/fixtures/node-typescript/ok.ts, test/fixtures/node-typescript/sum.ts, test/lib/runLintWithFixtures.js, test/node-typescript.js
[node/no-missing-import](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-missing-import.md) has been added into `plugin:node/recommended` since v10.
The rule only searches `[".js", ".json", ".node"]` extensions so the rule is always failed with TypeScript(`.ts`) files.
This PR fixes the problem.
I'd like to merge and release this as soon as possible because now most PRs for `cybozu/eslint-config` v9 are being failed due to this 🙏
=> fix: fail node/no-missing-import rule on TS files

lib/react.js, package-lock.json, package.json
Currently, we don't specify any version for React so we see the following warning when running ESLint with a preset includes `react`.
```
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
```
In this PR, I use `detect` option for the warning, which is an option to detect a version from the installed React version.
In addition to that, I've added `react` as a `devDependency` because of detecting React version.
=> fix: use detect option for React version

lib/typescript.js, package-lock.json, package.json, test/base-test.js, test/es5-test.js, test/fixtures/base/error.js, test/fixtures/es5/error.js, test/flowtype-test.js, test/globals-kintone-test.js, test/kintone-test.js, test/lib/runLintWithFixtures.js, test/node-test.js, test/node-typescript.js, test/presets-test.js, test/prettier-test.js, test/react-test.js, test/react-typescript-test.js, test/typescript-test.js
ESLint v7 has been released so we'd like to support ESLint v7.
https://eslint.org/blog/2020/05/eslint-v7.0.0-released
**THIS PR IS A BREAKING CHANGE because this drops to support ESLint v6.**
- Drop support ESLint v6
- Enable new rules in `@typescript-eslint/recommended`
- [`@typescript-eslint/no-extra-non-null-assertion`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-extra-non-null-assertion.md)
- [`@typescript-eslint/no-extra-semi`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-extra-semi.md)
- [`@typescript-eslint/no-non-null-asserted-optional-chain`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-non-null-asserted-o …
=> Support ESLint v7

.github/workflows/lint.yml, .github/workflows/test.yml
Currently, Renovate doesn't work as I expected, and I guess that the reason is that we only run GItHub Actions for branches that has a PR, which causes a pending commit status and Renovate skips creating a PR due to the status.
To prove this is correct, I've changed to run GitHub Actions for branches that Renovate creates. This is not a permanent solution, which is only for testing.
=> ci: run GitHub Actions for branch push by Renovate

.github/workflows/lint.yml, .github/workflows/test.yml, package.json, test/fixtures/node/error.js, test/node-test.js
I've made several changes based on #423
I've also tidied up some extra line and space and update lint.yml so that it'll make updating the Node version easier in the future.
This will closes #423
=> chore!: drop Node v10 support because of EOL

README.md
https://github.com/cybozu/eslint-config/blob/master/CHANGELOG.md#1300-2021-04-28 
With this change, the description of a11y is no longer needed.
=> docs: Removed the cautionary statement about a11y

README.md
BREAKING CHANGE: drop Prettier v1 support
I've updated `eslint-plugin-prettier` to v4 (#479) and  the version no longer supports Prettier v1 so we have to drop Prettier v1 support.
=> docs!: drop Prettier v1 support

README.md, lib/react.js, test/fixtures/react/ok.jsx
Fixed #450
I added "plugin:react/jsx-runtime" for React 17 based on the following statement.
> If you are using the new JSX transform from React 17, extend react/jsx-runtime in your eslint config (add "plugin:react/jsx-runtime" to "extends") to disable the relevant rules.
https://github.com/yannickcr/eslint-plugin-react#configuration
=> feat!: React 17 support 

.github/workflows/lint.yml, .github/workflows/test.yml, package.json
BREAKING CHANGE: Node v12 is no longer supported
Node v12 is no longer supported, so we can remove the support.
=> chore: drop Node v12 support, and add v18 support

.github/workflows/lint.yml, .github/workflows/test.yml, package.json
BREAKING CHANGE: Drop Node v14 support
Node v14 reached EOL, so we've dropped Node v14 support. I've also added Node v20 support, which is the next LTS version.
=> chore: Drop Node v14 support and add v20 support

lib/react.js
To prevent performance degradation, I added a rule to prohibit defining components within components in React.
Defining components within components can cause unnecessary re-rendering. 
- Enable: [`react/no-unstable-nested-components`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unstable-nested-components.md)
=> BREAKING CHANGE(react): add react/no-unstable-nested-components rule as error

lib/typescript.js, test/fixtures/react-typescript/error.tsx, test/fixtures/typescript/error.ts, test/react-typescript-test.js, test/typescript-test.js
I have added code that avoids the `"false positive"` problem of the eslint/no-shadow rule for TypeScript code discussed in `"typescript-eslint"` issue below.
Please see this issue for more detailed information. 
https://github.com/typescript-eslint/typescript-eslint/issues/2483
=> fix: false positive of no-shadow rule for TypeScript

.github/workflows/test.yml
Changed node versions used in CI test.
- before : `[16.x, 18.x, 20.x]`
- after : `[18.x, 20.x, 22.x]`
The current(2024/09) support status of each Node version is as follows
- 16 : deprecated
- 18 : maintenance mode
- 20 : Active as LTS
- 22 : cuttent version
So, CI test should be run in three environments: v18, v20, and v22.
`engines` in `package.json` has been `>= 18` for some time, so it looks good to drop v16.
=> ci: update node versions in ci test

README.md
README contains `.eslint.config.js`, but the correct name is `eslint.config.js`(leading dot is not necessary).
=> docs: fix README typo in config file name

flat/presets/base.js, test/flat/preset-base-test.js
Introduce a new `base` preset under `flat/preset` that directly provides the config from `flat/lib`.
In the previous Config system, users could easily extend the `lib/base` config by simply writing `{extends: '@cybozu'}`. However, there is no equivalent preset for FlatConfig that distributes only the rules from `flat/lib/base`.
As a result, users who previously wrote their config as `{extends: '@cybozu'}` have no alternative method in FlatConfig.
To resolve this issue, I created a new `flat/preset/base.js` that extends only the `flat/lib/base` rules.Additionally, I added tests to ensure that `flat/lib/base` and `flat/preset/base.js` are equivalent.
=> feat: Add base config to flat preset

README.md, presets/kintone-customize-prettier.js, presets/kintone-customize.js, test/presets-test.js
Because Kintone has dropped supporting IE, we promote using the >ES6 edition in Kintone customize/plugin-in.
- add `kintone-customize` and `kintone-customize-prettier` presets
- update README.md
=> feat: add `kintone-customize` presets

package-lock.json, package.json
Added `@eslint/js` as a dependency.
Although `@eslint/js` was being used in files like `flat/lib/base.js`, it was not included as a dependency, so I added it.
=> fix(deps): add @eslint/js to dependencies

package-lock.json, package.json
Move @eslint/css from devDependencies to dependencies to fix module resolution errors when using
flat/presets/css-baseline.js.
When packages that depend on @cybozu/eslint-config try to use flat/presets/css-baseline.js, they encounter the
error:
`Error: Cannot find module '@eslint/css'`
This happens because @eslint/css was listed in devDependencies, which are not installed for packages that depend
on this config.
Moved @eslint/css from devDependencies to dependencies since it's required at runtime by the css-baseline
preset.
- Moved @eslint/css@^0.10.0 from devDependencies to dependencies
=> fix(deps): move @eslint/css from devDependencies to dependencies
